README.md

A couple more tiny nits for the README. I was reviewing it again today because I'm working on onboarding docs, and I noticed that we don't mention creating a Stedi account explicitly. Since the bootstrap is for new users, it seems possible that they may not have a Stedi account yet/not really understand that it's required for this bootstrap. I think it never hurts to be explicit!
I also just adjusted the requirements so they all start with action words and made a couple of other tiny tweaks. My goal is to make it easier to read/make things obvious for new users. For example, I think separating out deployment and requirements could be helpful, so I made that into a separate section. LMK if you disagree with any of these edits - thank you!

Update README Requirements

---

src/functions/edi/inbound/handler.ts
src/lib/deliverToDestination.ts
src/lib/processEdi.ts

- include envelope data when processing each inbound transaction set
- only invoke translate once per transaction set (not per destination)
- move mapping call to `deliverToDestination`
- fix input file deletion (only delete after entire file has been processed)
closes: #31

fix: include envelope data for processed inbound edi files

---

package-lock.json
package.json
src/functions/edi/inbound/handler.ts
src/lib/acks.ts
src/lib/destinations.ts
src/lib/types/PartnerRouting.ts
src/setup/bootstrap/createStashRecords.ts

I verified via the following stash config:
... that the header gets added successfully: 
I also verified that attempting to set `content-type` was rejected by Zod:
```
INFO ZodError: [ { "validation": "regex", "code": "invalid_string", "message": "Invalid", "path": [ "transactionSets", 1, "destinations", 0, "destination", "headers", "content-type" ] } ]
```
I also tested all of the supported verbs:
Closes: #22

feat: add support for user-defined headers and verbs for webhook destinations

---

src/functions/edi/outbound/handler.ts
src/functions/ftp/external-poller/handler.ts
src/functions/ftp/external-poller/pollers/ftpPoller.ts
src/functions/ftp/external-poller/pollers/remotePoller.ts
src/functions/ftp/external-poller/pollers/sftpPoller.ts
src/lib/destinations.ts
src/lib/types/Destination.ts
src/lib/types/PartnerRouting.ts
src/lib/types/RemoteConnectionConfig.ts

New destination config (password scrubbed):
Example output on delivery:
Closes: #48

feat: add support for `sftp` destination

---

src/lib/deliveryManager.ts
src/lib/destinations/bucket.ts
src/lib/destinations/function.ts
src/lib/destinations/sftp.ts
src/lib/destinations/webhook.ts
src/lib/functions.ts
src/lib/types/Destination.ts
src/scripts/execute.ts
src/setup/deploy.ts
src/setup/destroy.ts

I added a "hello-world" function destination, and tested with both JSON (`edi-inbound`) and string (`edi-outbound`) payloads, both with and without `additionalInput` for the function:
example config (one entry with the optional `additionalInput` property and one without):
Closes #50

feat: add support for `function` destination

---

.gitignore
package.json
src/functions/edi/inbound/handler.ts
src/functions/edi/outbound/handler.ts
src/lib/archive/__tests__/archiveFile.unit.ts
src/lib/resolveGuide.ts
src/lib/types/OutboundEvent.ts
src/resources/X12/5010/850/outbound.json

When reading EDI, if multiple guides exist for a given transaction set,
resolve the correct guide by matching the envelope release with the
guide release.
When writing EDI, allow user to specify a release. Bootstrap will select
the guide for writing based on the release if multiple guides for the
transaction set are found.
Safe to upgrade.
When reading EDI, If existing users have a guide which does not match
the release of the EDI they are receiving then it will continue to
select the same guide. Logic only changes when there are multiple guides
for the same transaction set, which would previously generate an error.
When writing EDI, users must pass in a new "release" parameter to select
a guide when there are multiple guides for the same transaction set. An
error is generated if a guide …

feat: multi txns

---

.env.test
.github/workflows/pr.yaml
package.json
src/functions/edi/inbound/__fixtures__/events.ts
src/functions/edi/inbound/__tests__/handler.success-with-ack.ts
src/functions/edi/inbound/handler.ts
src/lib/archive/__tests__/archiveFile.unit.ts
src/lib/constants.ts
src/lib/deliveryManager.ts
src/lib/destinations/webhook.ts
src/lib/environment.ts
src/lib/processEdi.ts
src/lib/resolveGuide.ts
src/lib/testing/testHelpers.ts
src/setup/bootstrap.ts
src/setup/bootstrap/createProfiles.ts
src/setup/configureBuckets.ts
src/setup/deploy.ts
src/setup/enableBucketNotifications.ts
src/setup/migrate.ts

- Test covers the happy path for inbound processing, including ACKs.
- Adds Github Workflow for running test suite on PRs.
- Also improves how dotenv is used, by added a dedicated `.env.test` file that is passed to the ava runs via in package.json script. This helps keep any runtime config from `.env` from affecting test outputs.

feat: add test coverage to inbound function

---

package-lock.json
package.json
src/lib/__tests__/deliveryManager.unit.ts
src/lib/deliveryManager.ts
src/lib/destinations/as2.ts
src/lib/testing/testHelpers.ts
src/lib/types/Destination.ts

- add `as2` destination type (writes to bucket, then starts file transfer via AS2 SDK -- implementation consistent with `write-edi-demo`)
- add unit tests for `deliveryManager`
- add `sinon` dev dependency for stubbing sftp client calls
Closes: #49

feat: add `as2` destination type

---

src/lib/__tests__/deliveryManager.unit.ts
src/lib/deliveryManager.ts
src/lib/destinations/as2.ts
src/lib/destinations/bucket.ts
src/lib/destinations/sftp.ts

`destinationFilename` was optional, but in practice is always being sent by callers (as the destination type isn't considered by the caller, so it always includes a filename in case one is needed)

feat: make `destinationFilename` required property

---

.github/workflows/scheduled-ftp-poller.yaml
README.md
src/functions/ftp/external-poller/README.md
src/lib/types/RemoteConnectionConfig.ts

- adds new README for external poller
- adds link to new README from main README (also introduced a lot of prettier changes)
- makes `secure` and `secureOption` optional attributes on FTP connection details (aligns with ftp module default behavior)
- adds scheduled GH action to poll remote SFTP server (first part of moving previous "demo loop" over to bootstrap)

feat: ftp / sftp poller docs

---

.github/workflows/scheduled-write-edi.yaml
package.json

This replaces the previous scheduled task in the now-archived `write-edi-demo` repository:
- adds new `write-edi` npm script
- adds scheduled GH action to invoke `edi-outbound`  (new Stedi API key repository secret already added to support this)

feat: add scheduled task to invoke edi-outbound workflow

---

src/lib/__tests__/deliveryManager.unit.ts
src/lib/destinations/function.ts
src/lib/functions.ts
src/lib/types/Destination.ts

**Previous behavior:**
When invoking a destination Stedi function, the downstream function would be invoked with an input object in the following structure:
```typescript
{
additionalInput: <ADDITIONAL_INPUT_FROM_CONFIG>,
payload: <DESTINATION_PAYLOAD>,
}
```
This opinionated format made it impossible to, for example, invoke the `edi-outbound` function with the result of a mapping operation to automatically send an outbound EDI file. Customer #globecommerce-stedi encountered a use case where this would be useful.
**Updated behavior:**
Now the downstream function will be invoked with the raw destination payload, and if applicable the `additionalInput` from the configuration as well:
```typescript
{
...payload,
...additionalInput, // intentionally included second to support a use case of …
```

feat: use un-opinionated payload when invoking destination Stedi functions

---

src/lib/__tests__/deliveryManager.unit.ts
src/lib/destinations/bucket.ts

If an object is uploaded to a bucket with a leading slash (`/`) in the prefix, it leads to confusing behavior. This has definitely tripped me up in the past, and recently [tripped up a customer as well](https://stedi-inc.slack.com/archives/C04UZCY4SUB/p1679516175450919?thread_ts=1679505676.033679&cid=C04UZCY4SUB). To avoid this confusion, any leading slashes can be removed from the path when delivering to a bucket destination.

feat: remove leading slashes from path when delivering to bucket destination

---

src/lib/__tests__/deliveryManager.unit.ts
src/lib/types/Destination.ts

A customer [needs to use privateKey + username password](https://stedi-inc.slack.com/archives/C04MDD11WHG/p1679511861118429?thread_ts=1679325106.165069&cid=C04MDD11WHG) authentication for their trading partner's SFTP. My initial thought was to try and just pass through all available SSH/SFTP connection options from the library we use, but I wasn't able to find a good way to go from an existing TS type to a Zod schema, so we can just add options as-needed for now.
Will open a mirror PR against the engine branch as well

feat: support optional privateKey and passphrase in sftp config

---

src/scripts/restore.ts

We hit this bug when migrating a customer, restore script was only replacing the first instance of the guideIds.

fix: ensure all guideIds are replaced by restore script

---

.github/workflows/pr.yaml
src/functions/edi/inbound/__tests__/handler.success-with-ack.ts
src/functions/edi/inbound/handler.ts
src/lib/__tests__/deliveryManager.unit.ts
src/lib/__tests__/replication.unit.ts
src/lib/destinations/bucket.ts
src/lib/replication.ts
src/lib/types/ReplicationConfig.ts

- adds support for replicating inbound documents to destinations, via `bootstrap|replication-config` stash key using existing destinations schemas
- adds `legacy` branch to PR workflow config
- adds fix for object keys when destination bucket path is empty string (don't prefix key with `/`)

feat(legacy): add support for replicating inbound documents

---

src/functions/edi/inbound/__fixtures__/events.ts
src/functions/edi/inbound/__tests__/handler.success.ts
src/functions/edi/inbound/handler.ts

As the `edi-inbound` function only accepts `transaction.processed` events, we can tighten the input event type and improve on the filename prefix generation to leverage details from the event.

feat: enforce strict input type for edi-inbound, improve filename prefix based on stricter input

---

src/functions/edi/acknowledgment/__tests__/handler.invalid-config.ts
src/functions/edi/acknowledgment/handler.ts
src/functions/edi/outbound/handler.ts
src/functions/ftp/external-poller/handler.ts
src/lib/clients/stash.ts
src/lib/errorFromFunctionEvent.ts
src/lib/errorFromStashConfiguration.ts
src/lib/loadFileErrorDestinations.ts
src/lib/loadTransactionDestinations.ts

When a user sets a configuration in Stash that is not valid against the schema, return an error message that maximises the chance the user can understand and resolve the issue themselves. Sets an exception name that is more descriptive (either a stash issue or a function event issue), and sets the context.details property to the zod issues array, which contains the specific validation errors. Include either the stash key name or the function name in the error message.
Error returned from a function now looks like:
```
{
"context": {
"rawError": {
"context": {
"details": [
{
"code": "invalid_type",
"expected": "array",
"received": "undefined",
"path": [
"generateFor"
],
"message": "Required"
},
{
"code": "unrecognized_keys",
"keys": [
"invalidValue"
],
"path": [],
"message": "Unrecognized …
```

feat: include descriptive error name and details for schema parse errors

---

README.md
package.json
src/functions/edi/inbound/__tests__/handler.release.ts
src/functions/edi/inbound/handler.ts
src/functions/edi/outbound/handler.ts
src/lib/deliveryManager.ts
src/lib/types/Destination.ts

Destinations can specify a 'release' property. An inbound or outbound transaction will only be sent to a destination if the payload (inbound envelope or outbound metadata) release matches the destination release. If the destination does not specify a release then it will receive all matching transaction sets.
This follows the existing pattern for usage indicator code.

feat: allow destination filtering based on release

---

package.json
src/migrations/002-engine-preview.ts

also, adds back missing `configure-storage` script to package.json

fix: issues with case comparisons on profile ids during migration

---

src/setup/deploy.ts

We were previously swallowing all errors trying to create functions/bindings, presuming it was ResourceNotFound - we now check the error type and throw/continue accordingly.

feat: show errors deploying functions / bindings

---

src/functions/edi/inbound/handler.ts
src/functions/edi/outbound/handler.ts
src/functions/events/file-error/handler.ts
src/lib/__tests__/deliveryManager.unit.ts
src/lib/deliveryManager.ts
src/lib/destinations/as2.ts
src/lib/destinations/bucket.ts
src/lib/destinations/sftp.ts
src/lib/destinations/stash.ts
src/lib/execution.ts
src/lib/types/DestinationAS2.ts
src/lib/types/DestinationBucket.ts
src/lib/types/DestinationSftp.ts
src/schemas/destination-as2.json
src/schemas/destination-bucket.json
src/schemas/destination-sftp.json

- adds support for `baseFilename` for as2, bucket, and sftp destinations (required in order to support multiple output files on the same destination from a single input event)
- refactors `deliveryManager` input to use `PayloadMetadata` instead of `destinationFilename`, as not all destination types support filenames

feat: add support for `baseFilename` for as2, bucket, and sftp destinations

---

src/functions/edi/outbound/__tests__/handler.legacy.ts
src/functions/edi/outbound/handler.ts
src/lib/types/OutboundEvent.ts

Updates `edi-outbound` to accept and transform legacy input, intended to allow production Bootstrap `legacy` branch usage to be upgraded to Core / `main` without interruption. 
Closes https://github.com/Stedi-Demos/bootstrap/issues/143

feat: support legacy input for edi-outbound function

---

src/functions/edi/acknowledgment/__tests__/handler.invalid-config.ts
src/functions/edi/inbound/handler.ts
src/functions/edi/outbound/handler.ts
src/functions/events/file-error/handler.ts
src/functions/ftp/external-poller/handler.ts
src/lib/errorWithContext.ts
src/lib/execution.ts
src/setup/deploy.ts

Previously the error message was a hard-coded 'execution failed', this meant the DLQ did not show descriptive messages. The stack trace was also limited and did not show the full error trace due to a new error object being constructed.
Now the ErrorWithContext uses the 'cause' property where possible to preserve the original stack trace, and the error message re-uses the original error message. The ErrorWithContext 'context' property has been simplified to make it more usable.
Also fixes deployment error logging, which previously did not print error objects.
Before:
Now:
With good stack trace:

fix: use the error message from the original exception when returning

---

package.json
src/optional-functions/billing/usage-poller/Configuration.ts
src/optional-functions/billing/usage-poller/__tests__/handler.usage-threshold.ts
src/optional-functions/billing/usage-poller/configuration.json
src/optional-functions/billing/usage-poller/constants.ts
src/optional-functions/billing/usage-poller/deploy.ts
src/optional-functions/billing/usage-poller/handler.ts
src/scripts/schema-zod-types.ts

Looks at the current billing period usage to project end-of-month costs. Triggers a webhook or function if the end-of-month costs are above a list of threshold spending levels.

feat: add optional billing usage poller function

---

src/functions/ftp/external-poller/handler.ts
src/functions/ftp/external-poller/types.ts
src/lib/types/RemoteConnectionConfig.ts

- capture timestamp of current poll before retrieving file list (instead of at the end of processing)
- update timestamp of current poll operation if a file is encountered with a newer value than the currently tracked one (catch files that show up during processing somehow)
- add option for ignoring timestamps completely (always download the file, regardless of modification time)

fix: remote poller timestamp tracking

---

src/functions/edi/outbound/handler.ts

also slightly reformat the source property structure to match the edi-inbound source structure better.

feat: return generate envelope data in edi-outbound function

---

src/functions/edi/inbound/__tests__/handler.direction.ts
src/functions/edi/inbound/handler.ts
src/functions/edi/outbound/__tests__/handler.direction.ts
src/functions/edi/outbound/handler.ts
src/lib/types/Destination.ts
src/schemas/transaction-destinations.json

Add ability to use a destination for only one direction, "inbound" or "outbound", when the same transaction set is used for both sending and receiving in the same partnership. Property is optional and non-breaking change.

feat: add property direction to only run destination in one direction

---

README.md

@RossWilliams I deployed bootstrap today because I'm working on Core docs, and I realized that we don't really tell anyone what gets deployed and where to find it. I added in some context that I am hoping will be helpful for new folks. We ask them to jump right into testing, but I think it's helpful to show them what they can expect to find in their account. 
Stedi app is kind of disjointed right now (it's not like you see a dashboard of all your resources or anything), so I could imagine someone not knowing where to look for things/that things exist if they're new.  Please flag anything I got wrong. LMK what you think!

Add description of deployed resources to README

---

package-lock.json
package.json
src/functions/edi/outbound/__tests__/handler.app-id-overrides.ts
src/functions/edi/outbound/__tests__/handler.direction.ts
src/functions/edi/outbound/__tests__/handler.guideless-997.ts
src/functions/edi/outbound/__tests__/handler.legacy.ts
src/functions/edi/outbound/__tests__/handler.success-without-mapping.ts
src/functions/edi/outbound/handler.ts
src/migrations/002-engine-preview.ts
src/setup/bootstrap/createProfiles.ts

- upgrade partners SDK
- change GS ID (application ID) logic for `edi-outbound` to use the following process for choosing ID to use:
- first, check outbound transaction configuration
- second, check for a default application id for the profile
- if neither of the above are set, use the same value as the ISA ID

fix: upgrade partners sdk, change app id handling to reflect latest api

---

.github/workflows/pr.yaml
src/functions/edi/inbound/__fixtures__/events.ts
src/functions/edi/inbound/__tests__/handler.no-transaction-set-configured.ts
src/functions/edi/inbound/__tests__/handler.source-is-artifact-bucket.ts
src/functions/edi/inbound/__tests__/handler.success.ts
src/functions/edi/inbound/handler.ts

when using Core's remote sftp poller, the poller adds the document to Core's artifact bucket and sets this as the input when sending transaction processed events. In these cases the edi-inbound function should not attempt to delete the input since Core handles the work and the input is read-only.
Fix tests which use the artifact bucket as the source input by default.

fix: do not delete inbound edi file when source is core artifact bucket
